### ISSUE TITLE
Can't parse Japanese PDF.

### ISSUE THREAD

**Issue by hhhhub000** [planio-gmbh/plaintext#8]
I try to parse pdf including japanse.
such as "ああああ".
But result is "????"

plaintext use following cmd:
/usr/local/bin/pdftotext -enc UTF-8 __FILE__  -

So, pdftotext result is UTF-8 binary bytes.

But code is...
```
ExternalCommandHandler
    def read(io, max_size = nil)
      Plaintext::CodesetUtil.to_utf8 io.read(max_size), "ASCII-8BIT" ★
```
and Plaintext::CodesetUtil.to_utf8
```
      enc = (encoding.nil? || encoding.size == 0) ? 'UTF-8' : encoding
      if enc.upcase != 'UTF-8'
        str.force_encoding(enc)  ★forse set to ASCII-8bit
        str = str.encode('UTF-8', invalid: :replace,   ★ASCII-8bit->UTF-8. But str is UTF-8 before encode.
                         undef: :replace, replace: '?')
```
I modify code follwing. PDF is parsed correctry.
`Plaintext::CodesetUtil.to_utf8 io.read(max_size), "ASCII-8BIT"` 
->
`Plaintext::CodesetUtil.to_utf8 io.read(max_size), "UTF-8"`

**Comment by wielinde** [comment]
Resolved with plaintext version `0.3.2`
